#
# SurvivalBingo Config
# Developed By Nulli Team (Efe, horyu1234)
#
config: 1.0
#
# teleport-level: 1 ---> 게임 시작시 작동할 텔레포트 방법
# (-1: 설정된 위치로 이동)
# (0: 이동하지 않음)
# (1: 최대 거리 100칸 이내로 랜덤 이동)
# (2: 최대 거리 1000칸 이내로 랜덤 이동)
# (3: 최대 거리 10000칸 이내로 랜덤 이동)
#
# goal-bingo-count: 1 ---> 우승에 필요한 목표 빙고 수
#
# max-team-difference: -1 ---> 팀간 멤버 수 최대 차이
# (-1: 작동 안함)
# (0 이상: 해당 값보다 팀 인원의 차이가 크다면, 게임 시작 불가능)
#
# chat-prefix: true ---> 채팅시에 접두사로 자신이 속한 팀을 표시할 지 여부
#
# on-start: 게임 시작 시
#   heal: true 체력 최대
#   feed: true 배고픔 최대
#   remove-potion-effects: true 모든 포션 효과 제거
#   clear-inventory: true 인벤토리 초기화
# freeze-food-level: false 배고픔 비활성화
#
# bingo-item-list: ---> 랜덤으로 빙고판을 생성할 때 사용할 아이템들
# - "159:3" ---> 아이템 코드 또는 아이템 이름 (ex: - "STONE" OR - "1")
# 아이템 이름 참고: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
#
teleport-level: 1
goal-bingo-count: 1
max-team-difference: -1
chat-prefix: true

on-start:
  heal: true
  feed: true
  remove-potion-effects: true
  clear-inventory: true
freeze-food-level: false

teleport-location:
  red:
    world: "world"
    x: 50
    y: 100
    z: 50
    yaw: 0
    pitch: 0
  blue:
    world: "world"
    x: -50
    y: 100
    z: -50
    yaw: 0
    pitch: 0

bingo-item-list:
  easy:
  - "65"
  - "139"
  - "6:2"
  - "339"
  - "389"
  - "375"
  - "373"
  - "77"
  - "416"
  - "296"
  - "415"
  - "301"
  - "320"
  - "1:2"
  - "24"
  - "31:1"
  - "355"
  - "346"
  - "185"
  - "390"
  - "327"
  - "102"
  - "80"
  - "147"
  - "33"
  - "328"
  - "131"
  - "66"
  - "18"
  - "259"

  hard:
  - "172"
  - "170"
  - "23"
  - "413"
  - "171:9"
  - "386"
  - "368"
  - "347"
  - "32"
  - "398"
  - "425:2"
  - "395"
  - "376"
  - "161"
  - "95:7"
  - "19"
  - "322"
  - "179"
  - "407"
  - "400"
  - "354"
  - "276"
  - "145:2"
  - "98:1"
  - "155:2"
  - "123"
  - "84"
  - "420"
  - "388"
  - "139:1"

  insane:
  - "354"
  - "413"
  - "327"
  - "425:6"
  - "116"
  - "179"
  - "103"
  - "370"
  - "165"
  - "414"
  - "388"
  - "349:2"
  - "32"
  - "145:2"
  - "403"
  - "191"
  - "373:8227"
  - "373:16388"
  - "322:1"
  - "169"
  - "385"
  - "375"
  - "397:1"
  - "130"
  - "179"
  - "329"
  - "57"
  - "133"
  - "98:2"
  - "19"
  - "399"